/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entities.Kamar;
import entities.Reservation;
import entities.Tamu;
import java.awt.Frame;
import java.util.List;
import models.KamarDAO;
import models.KamarSQLite;
import models.ReservationDAO;
import models.ReservationSQLite;
import models.TamuDAO;
import models.TamuSQLite;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class CheckOutForm extends javax.swing.JDialog {

    ReservationDAO reservationDAO;
    TamuDAO tamuDAO;
    KamarDAO kamarDAO;
    MainPage mainPage; // Referensi ke MainPage
    List<String> noIdList;
    
    /**
     * Creates new form CheckOutDialog
     */
    public CheckOutForm(java.awt.Frame parent, boolean modal, MainPage mainPage) {
        super(parent, modal);
        this.mainPage = mainPage; // Simpan referensi MainPage
        initComponents();
        reservationDAO = new ReservationSQLite();
        tamuDAO = new TamuSQLite();
        kamarDAO = new KamarSQLite();
        refreshData();
    }
    
    public void refreshData(){
        tampil_noId();
    }
    
    public void tampil_noId(){
        noIdList = reservationDAO.getId();
        cmbNoId.removeAllItems();
        for (String id : noIdList) {
            cmbNoId.addItem(id);
        }
    }
    
    public void onIdSelected(){
        String selectedId = (String) cmbNoId.getSelectedItem();
        if (selectedId != null) {
            Reservation reservation = reservationDAO.get(Integer.parseInt(selectedId));
            Tamu tamu = tamuDAO.getNoKtp(reservation.getNoKtp());
            Kamar kamar = kamarDAO.get(reservation.getNoKamar());

            lblKtp.setText(tamu.getNoKtp());
            lblTamu.setText(tamu.getNama());
            lblKamar.setText(String.valueOf(kamar.getNoKamar()));
            lblCheckInDate.setText(reservation.getCheckInDate());
            lblDepo.setText(String.valueOf(reservation.getDeposit()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKtp = new javax.swing.JLabel();
        lblTamu = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        lblNoKtp = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNoKamar = new javax.swing.JLabel();
        lblTglIn = new javax.swing.JLabel();
        lblDp = new javax.swing.JLabel();
        lblCheckInDate = new javax.swing.JLabel();
        lblTglOut = new javax.swing.JLabel();
        txtTglOut = new javax.swing.JTextField();
        lblDepo = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        lblReservasi = new javax.swing.JLabel();
        cmbNoId = new javax.swing.JComboBox<>();
        lblKamar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblKtp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKtp.setText("No KTP");

        lblTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamu.setText("Nama Tamu");

        lblCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCheckOut.setText("Check Out Tamu");

        lblNoKtp.setText("No KTP");

        lblNama.setText("Nama");

        lblNoKamar.setText("Nomor Kamar");

        lblTglIn.setText("Tanggal Check In");

        lblDp.setText("Deposit");

        lblCheckInDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckInDate.setText("Tgl Check In");

        lblTglOut.setText("Tanggal Check Out");

        lblDepo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepo.setText("Deposit");

        btnCheckOut.setBackground(new java.awt.Color(204, 204, 255));
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        lblReservasi.setText("Id Reservasi");

        cmbNoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNoIdActionPerformed(evt);
            }
        });

        lblKamar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKamar.setText("No Kamar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTglIn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNoKtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNoKamar))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTglOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTglOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDepo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblTamu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblKtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCheckOut)
                            .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCheckOut)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReservasi)
                        .addGap(18, 18, 18)
                        .addComponent(lblNoKtp)
                        .addGap(12, 12, 12)
                        .addComponent(lblNama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKtp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTamu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKamar)
                            .addComponent(lblNoKamar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCheckInDate)
                            .addComponent(lblTglIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTglOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTglOut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDepo)
                            .addComponent(lblDp))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnCheckOut)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        String selectedId = (String) cmbNoId.getSelectedItem();
        if (selectedId == null) {
            JOptionPane.showMessageDialog(this, "Please select a reservation ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Reservation reservation = reservationDAO.get(Integer.parseInt(selectedId));
        if (reservation == null) {
            JOptionPane.showMessageDialog(this, "Reservation not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String checkOutDate = txtTglOut.getText();
        
        // Mengupdate data checkout dengan date dan menghitung otomatis total price
        reservationDAO.checkOut(Integer.parseInt(selectedId), checkOutDate);

        JOptionPane.showMessageDialog(this, "Check out successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Refresh data in MainPage
        mainPage.refreshData();
        dispose();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void cmbNoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNoIdActionPerformed
        // TODO add your handling code here:
        onIdSelected();
    }//GEN-LAST:event_cmbNoIdActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JComboBox<String> cmbNoId;
    private javax.swing.JLabel lblCheckInDate;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblDepo;
    private javax.swing.JLabel lblDp;
    private javax.swing.JLabel lblKamar;
    private javax.swing.JLabel lblKtp;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoKamar;
    private javax.swing.JLabel lblNoKtp;
    private javax.swing.JLabel lblReservasi;
    private javax.swing.JLabel lblTamu;
    private javax.swing.JLabel lblTglIn;
    private javax.swing.JLabel lblTglOut;
    private javax.swing.JTextField txtTglOut;
    // End of variables declaration//GEN-END:variables
}
