/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entities.Kamar;
import entities.Reservation;
import entities.Tamu;
import java.util.List;
import models.KamarDAO;
import models.KamarSQLite;
import models.ReservationDAO;
import models.ReservationSQLite;
import models.TamuDAO;
import models.TamuSQLite;

/**
 *
 * @author lenovo
 */
public class CheckInForm extends javax.swing.JDialog {

    ReservationDAO reservationDAO;
    TamuDAO tamuDAO;
    KamarDAO kamarDAO;
    MainPage mainPage; // Referensi ke MainPage
    List<String> noIdList;
    
    /**
     * Creates new form CheckInDialog
     */
    public CheckInForm(java.awt.Frame parent, boolean modal, MainPage mainPage) {
        super(parent, modal);
        this.mainPage = mainPage; // Simpan referensi MainPage
        initComponents();
        reservationDAO = new ReservationSQLite();
        tamuDAO = new TamuSQLite();
        kamarDAO = new KamarSQLite();
        refreshData();
    }

    public void refreshData(){
        tampil_noId();
    }
    
    public void tampil_noId(){
        noIdList = reservationDAO.getId();
        cmbNoId.removeAllItems();
        for (String id : noIdList) {
            cmbNoId.addItem(id);
        }
    }
    
    public void onIdSelected(){
        String selectedId = (String) cmbNoId.getSelectedItem();
        if (selectedId != null) {
            Reservation reservation = reservationDAO.get(Integer.parseInt(selectedId));
            Tamu tamu = tamuDAO.getNoKtp(reservation.getNoKtp());
            Kamar kamar = kamarDAO.get(reservation.getNoKamar());

            lblKtp.setText(tamu.getNoKtp());
            lblTamu.setText(tamu.getNama());
            lblKamar.setText(String.valueOf(kamar.getNoKamar()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoId = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNoKamar = new javax.swing.JLabel();
        lblTgl = new javax.swing.JLabel();
        lblDp = new javax.swing.JLabel();
        lblKtp = new javax.swing.JLabel();
        lblTamu = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        btnCheckIn = new javax.swing.JButton();
        lblNoKtp = new javax.swing.JLabel();
        lblReservasi = new javax.swing.JLabel();
        lblKamar = new javax.swing.JLabel();
        txtDp = new javax.swing.JTextField();
        cmbNoId = new javax.swing.JComboBox<>();

        lblNoId.setText("Id Tamu");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCheckIn.setText("Check In Tamu");

        lblNama.setText("Nama");

        lblNoKamar.setText("Nomor Kamar");

        lblTgl.setText("Tanggal Check In");

        lblDp.setText("Deposit");

        lblKtp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKtp.setText("No KTP");

        lblTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamu.setText("Nama Tamu");

        btnCheckIn.setBackground(new java.awt.Color(204, 204, 255));
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        lblNoKtp.setText("No KTP");

        lblReservasi.setText("Id Reservasi");

        lblKamar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKamar.setText("No Kamar");

        cmbNoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNoIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNoKtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCheckIn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblReservasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNoKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKtp, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(lblTamu, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(lblKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCheckIn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReservasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNoKtp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNoKamar)
                        .addGap(18, 18, 18)
                        .addComponent(lblTgl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblKtp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTamu))
                            .addComponent(cmbNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDp)
                    .addComponent(txtDp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnCheckIn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNoIdActionPerformed
        // TODO add your handling code here:
        onIdSelected();
    }//GEN-LAST:event_cmbNoIdActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        String selectedId = (String) cmbNoId.getSelectedItem();
        if (selectedId != null) {
            int reservationId = Integer.parseInt(selectedId);
            String checkInDate = txtTanggal.getText();
            int deposit = Integer.parseInt(txtDp.getText());

            reservationDAO.checkIn(reservationId, checkInDate, deposit);
            mainPage.refreshData(); // Refresh data di MainPage
            dispose(); // Tutup dialog setelah check-in
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JComboBox<String> cmbNoId;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblDp;
    private javax.swing.JLabel lblKamar;
    private javax.swing.JLabel lblKtp;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoId;
    private javax.swing.JLabel lblNoKamar;
    private javax.swing.JLabel lblNoKtp;
    private javax.swing.JLabel lblReservasi;
    private javax.swing.JLabel lblTamu;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JTextField txtDp;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
