/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import javax.swing.WindowConstants;

/**
 *
 * @author lenovo
 */
public class MainPage extends javax.swing.JFrame {
    
    LoginDialog loginD;
    MainPanel mainPanel;
    BookingPanel bookPanel;
    ReservationPanel resvPanel;
    CardLayout layout;
    GuestPanel guestPanel;
    RoomsPanel roomPanel;
    CheckInForm checkinForm;
    CheckOutForm checkoutForm;
    

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        loginD = new LoginDialog(this, rootPaneCheckingEnabled);
        loginD.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        loginD.setVisible(true);
        
        layout = (CardLayout)this.MainPanel.getLayout();
        mainPanel = new MainPanel();
        roomPanel = new RoomsPanel(this); // Kirim referensi MainPage
        bookPanel = new BookingPanel(this); // Kirim referensi MainPage
        guestPanel = new GuestPanel();
        resvPanel = new ReservationPanel();
        
        MainPanel.add("main", mainPanel);
        MainPanel.add("kamar", roomPanel);
        MainPanel.add("booking", bookPanel);
        MainPanel.add("tamu", guestPanel);
        MainPanel.add("resv", resvPanel);
    }
    
    public void setMainPanel(String key){
        layout.show(MainPanel, key);
    }
    
    public MainPanel getMainPanel() {
        return mainPanel;
    }

    public void refreshData(){
        mainPanel.refreshData();
        roomPanel.refreshData();
        bookPanel.refreshData();
        resvPanel.refreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnAddKamar = new javax.swing.JButton();
        btnAddTamu = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnReservasi = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddKamar.setBackground(new java.awt.Color(204, 255, 204));
        btnAddKamar.setText("Data Kamar");
        btnAddKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKamarActionPerformed(evt);
            }
        });

        btnAddTamu.setBackground(new java.awt.Color(204, 204, 255));
        btnAddTamu.setText("Buku Tamu");
        btnAddTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTamuActionPerformed(evt);
            }
        });

        btnBooking.setBackground(new java.awt.Color(255, 204, 102));
        btnBooking.setText("Booking Kamar");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(255, 255, 204));
        MainPanel.setLayout(new java.awt.CardLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setText("Selamat Datang,");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("sherina");

        btnCheckIn.setBackground(new java.awt.Color(255, 204, 51));
        btnCheckIn.setText("Check-In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setBackground(new java.awt.Color(255, 153, 51));
        btnCheckOut.setText("Check-Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnReservasi.setBackground(new java.awt.Color(204, 255, 255));
        btnReservasi.setText("Lap Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("siMotel (Aplikasi Manajemen Hotel)");

        btnDashboard.setBackground(new java.awt.Color(255, 102, 51));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblWelcome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUsername))
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBooking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCheckIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCheckOut)
                        .addGap(67, 67, 67)
                        .addComponent(btnAddKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddTamu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReservasi)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        setMainPanel("booking");
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnAddKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKamarActionPerformed
        // TODO add your handling code here:
        setMainPanel("kamar");
    }//GEN-LAST:event_btnAddKamarActionPerformed

    private void btnAddTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTamuActionPerformed
        // TODO add your handling code here:
        setMainPanel("tamu");
    }//GEN-LAST:event_btnAddTamuActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        CheckInForm checkinForm = new CheckInForm(this, true, this);
        checkinForm.setVisible(true);
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        loginD.setVisible(true); //kembali ke form login7w
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        CheckOutForm checkoutForm = new CheckOutForm(this, true, this);
        checkoutForm.setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        setMainPanel("main");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        // TODO add your handling code here:
        setMainPanel("resv");
    }//GEN-LAST:event_btnReservasiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnAddKamar;
    private javax.swing.JButton btnAddTamu;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
