/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entities.Reservation;

/**
 *
 * @author lenovo
 */
public class RincianCheckin extends javax.swing.JDialog {

    Reservation reservation;
    
    /**
     * Creates new form RincianCheckin
     */
    public RincianCheckin(java.awt.Frame parent, boolean modal, Reservation reservation) {
        super(parent, modal);
        this.reservation = reservation;
        initComponents();
        detailDp();
    }
    
    private void detailDp(){
        //detail isi rincian dp
        lblIdResv.setText(String.valueOf(reservation.getId()));
        lblKtp.setText(reservation.getTamu().getNoKtp());
        lblTamu.setText(reservation.getTamu().getNama());
        lblKamar.setText(reservation.getKamar().getNoKamar());
        lblCheckInDate.setText(reservation.getCheckInDate());
        lblDepo.setText(String.valueOf(reservation.getDeposit()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrint = new javax.swing.JButton();
        lblNoKtp = new javax.swing.JLabel();
        lblDepo = new javax.swing.JLabel();
        lblReservasi = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblIdResv = new javax.swing.JLabel();
        lblNoKamar = new javax.swing.JLabel();
        lblTglIn = new javax.swing.JLabel();
        lblBills = new javax.swing.JLabel();
        lblDp = new javax.swing.JLabel();
        lblTamu = new javax.swing.JLabel();
        lblKtp = new javax.swing.JLabel();
        lblCheckInDate = new javax.swing.JLabel();
        lblKamar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-print-48.png"))); // NOI18N

        lblNoKtp.setText("Nomor KTP");

        lblDepo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepo.setText("Deposit");

        lblReservasi.setText("Id Reservasi");

        lblNama.setText("Nama");

        lblIdResv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdResv.setText("Id Reservasi");

        lblNoKamar.setText("Nomor Kamar");

        lblTglIn.setText("Tanggal Check In");

        lblBills.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblBills.setText("Rincian Sementara (Bukti DP)");

        lblDp.setText("Deposit");

        lblTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamu.setText("Nama Tamu");

        lblKtp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKtp.setText("No Ktp");

        lblCheckInDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckInDate.setText("Tgl Check In");

        lblKamar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKamar.setText("Kamar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBills)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReservasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNoKtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTglIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNoKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdResv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblKtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTamu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBills)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKtp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTamu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCheckInDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReservasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNoKtp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNoKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTglIn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDepo)
                    .addComponent(lblDp))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel lblBills;
    private javax.swing.JLabel lblCheckInDate;
    private javax.swing.JLabel lblDepo;
    private javax.swing.JLabel lblDp;
    private javax.swing.JLabel lblIdResv;
    private javax.swing.JLabel lblKamar;
    private javax.swing.JLabel lblKtp;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoKamar;
    private javax.swing.JLabel lblNoKtp;
    private javax.swing.JLabel lblReservasi;
    private javax.swing.JLabel lblTamu;
    private javax.swing.JLabel lblTglIn;
    // End of variables declaration//GEN-END:variables
}
