/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import entities.Kamar;
import helpers.DBConnect;
import helpers.TabelKamar;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import models.KamarDAO;
import models.KamarSQLite;

/**
 *
 * @author lenovo
 */
public class RoomsPanel extends javax.swing.JPanel {

    KamarDAO dao;
    MainPage mainPage; // Referensi ke MainPage
    List<Kamar> dataKamar;
    boolean editMode = false;

    /**
     * Creates new form RoomsPanel
     */
    public RoomsPanel(MainPage mainPage) {
        this.mainPage = mainPage; // Simpan referensi MainPage
        initComponents();
        dao = new KamarSQLite();
        refreshData();
    }

    private void clearInput() {
        txtNoKamar.setText("");
        txtTypeKamar.setText("");
        txtHarga.setText("");
        txtNoKamar.setEnabled(true);
        btnHapus.setEnabled(false);
    }

    public void refreshData() {
        dataKamar = dao.getAll();
        tblKamar.setModel(new TabelKamar(dataKamar));
        clearInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddKamar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKamar = new javax.swing.JTable();
        lblNoKamar = new javax.swing.JLabel();
        lblKamar = new javax.swing.JLabel();
        lblTypeKamar = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        txtNoKamar = new javax.swing.JTextField();
        txtTypeKamar = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        lblAddKamar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddKamar.setText("Tambah Data Kamar");

        tblKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKamar);

        lblNoKamar.setText("Nomor Kamar");

        lblKamar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKamar.setText("Data Kamar");

        lblTypeKamar.setText("Jenis Kamar");

        lblHarga.setText("Harga");

        btnSimpan.setBackground(new java.awt.Color(204, 204, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 153, 153));
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddKamar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNoKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTypeKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(txtTypeKamar)
                                    .addComponent(txtHarga))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddKamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoKamar)
                    .addComponent(txtNoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTypeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeKamar)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lblKamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String noKamar = txtNoKamar.getText();
        String jenisKamar = txtTypeKamar.getText();

        try {
            // Konversi hargaText ke int harga langsung
            int harga = Integer.parseInt(txtHarga.getText());

            Kamar kamar = new Kamar(noKamar, jenisKamar, harga, true);

            if (!editMode) {
                dao.insert(kamar);
            } else {
                dao.update(kamar);
                editMode = false; // Reset edit mode setelah meng-update
            }

            refreshData(); // Memperbarui tabel dan membersihkan input
        } catch (NumberFormatException e) {
            System.out.println("Input harga tidak valid: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Input harga tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (mainPage != null) {
            mainPage.refreshData(); // Refresh data di MainPage
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        dao.delete(txtNoKamar.getText());
        refreshData();
        if (mainPage != null) {
            mainPage.refreshData(); // Refresh data di MainPage
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKamarMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            editMode = true;
            btnHapus.setEnabled(true);

            int selectedRow = tblKamar.getSelectedRow();
            Kamar kamar = dataKamar.get(selectedRow);
            
            txtNoKamar.setText(kamar.getNoKamar());
            txtTypeKamar.setText(kamar.getJenisKamar());
            txtHarga.setText(String.valueOf(kamar.getHarga()));

            txtNoKamar.setEnabled(false);
        }
    }//GEN-LAST:event_tblKamarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddKamar;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKamar;
    private javax.swing.JLabel lblNoKamar;
    private javax.swing.JLabel lblTypeKamar;
    private javax.swing.JTable tblKamar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNoKamar;
    private javax.swing.JTextField txtTypeKamar;
    // End of variables declaration//GEN-END:variables
}
