/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aplikasi.hotel;

import gui.MainPage;
import static helpers.DBSetup.setupDatabase;
import java.text.ParseException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {
        setupDatabase();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
}
